import keyMirrorWithPrefix from "lib/keyMirrorWithPrefix";

export default keyMirrorWithPrefix({
  LIKES_MODAL: [
    'CLOSE',
    'LOAD_LIKES_SUCCESS',
    'LOAD_NEXT_LIKES_SUCCESS',
    'SHOW_MODAL',
    'SET_PAGE'
  ],
  GIFT_MODALS: [
    'BUY_MARKS',
    'PRESENT_MARKS',
    'BUY_GIFTS',
    'PRESENT_GIFTS',
    'CLOSE'
  ],
  BUY_COINS_FORM: [
    'LOAD_PRODUCTS_SUCCESS',
    'HANDLE_FIELD_CHANGE'
  ],
  DREAM_PAGE: [
    'LOAD_DREAM_START',
    'LOAD_DREAM_FAILED',
    'LOAD_DREAM_SUCCESS',
    'START_EDIT',
    'CANCEL_EDIT',
    'PHOTO_CHANGE',
    'FIELD_CHANGE',
    'SAVE_DREAM_SUCCESS'
  ],
  DREAMER_INFO: [
    'ADD_FRIEND_CLICK',
    'REMOVE_FRIEND_CLICK',
    'LOAD_DREAMER_INFO_SUCCESS',
    'LOAD_DREAMER_INFO_FAILED',
    'SEND_MESSAGE_CLICK',
    'UPDATE_STATUS'
  ],
  CREATE_DREAM: [
    'HANDLE_MENU_BTN_CLICK',
    'HANDLE_CLOSE_BTN_CLICK',

    'HANDLE_FIELD_CHANGE',

    'HANDLE_SELECT_PHOTO',
    'HANDLE_SAVE_IMAGE_CROPPER_MODAL',
    'HANDLE_CLOSE_IMAGE_CROPPER_MODAL',

    'HANDLE_CERTIFICATE_SELECT',
    'LOAD_CERTIFICATES_SUCCESS',
    'ADD_DREAM_SUCCESS'
  ],
  UPDATES_FEED: [
    'LOAD_UPDATES_START',
    'LOAD_UPDATES_SUCCESS',
    'LOAD_UPDATES_FAILED',
    'LOAD_NEXT_UPDATES_SUCCESS'
  ],
  EVENTS_FEED: [
    'LOAD_EVENTS_START',
    'LOAD_EVENTS_SUCCESS',
    'LOAD_EVENTS_FAILED',
    'LOAD_NEXT_EVENTS_SUCCESS'
  ],
  POSTS_FEED: [
    'INIT_WITH_PARAMS',

    'LOAD_POSTS_START',
    'LOAD_POSTS_SUCCESS',
    'LOAD_NEXT_POSTS_SUCCESS',
    'LOAD_POSTS_FAILED',

    'CREATE_POST_START',
    'CREATE_POST_SUCCESS',
    'CREATE_POST_FAILED',

    'EDIT_POST_BEGIN',
    'EDIT_POST_CANCEL',

    'UPDATE_POST_START',
    'UPDATE_POST_FAILED',
    'UPDATE_POST_SUCCESS'
  ],

  NOTIFICATIONS_LIST: [
    'NEW_MESSAGE',
    'CLOSE_NOTIFICATION',
    'NEW_MESSAGE_CLICK'
  ],
  LEADERS_BAR: [
    'LOAD_LEADERS_SUCCESS',
    'SHOW_ADD_MODAL',
    'CLOSE_ADD_MODAL',
    'ADD_PHOTO_SUCCESS'
  ],
  MESSENGER: [
    'CLOSE_CLICK',

    'LOAD_CONVERSATIONS_START',
    'LOAD_CONVERSATIONS_FAILED',
    'LOAD_CONVERSATIONS_SUCCESS',
    'LOAD_NEXT_CONVERSATIONS_SUCCESS',

    'OPEN_CONVERSATION',

    'MAIN_AREA_SCROLL',
    'LOAD_MESSAGES_LIST',
    'LOAD_PREVIOUS_MESSAGES',

    'NEW_MESSAGE'
  ],
  USER: [
    'LOAD_USER_SUCCESS',
    'MESSAGES_CLICK'
  ],
  DREAMERS_LIST: [
    'INIT_WIDGET',
    'LOAD_DREAMERS_START',
    'LOAD_DREAMERS_SUCCESS',
    'LOAD_NEXT_DREAMERS_SUCCESS',
    'LOAD_DREAMERS_FAILED',

    'SEND_MESSAGE_CLICK',
    'ADD_FRIEND_CLICK',
    'REMOVE_FRIEND_CLICK',
    'APPROVE_FRIEND_CLICK',
    'REJECT_FRIEND_CLICK',

    'INITIALIZE_FILTER',
    'FILTER_CHANGE'
  ],
  DREAMS_LIST: [
    'LOAD_DREAMS_START',
    'LOAD_DREAMS_SUCCESS',

    'LOAD_NEXT_DREAMS_SUCCESS',
    'LOAD_DREAMS_FAILED',

    'SORT_BY',
    'FILTER_CHANGE',

    'LIKE_CLICK_START',
    'LIKE_CLICK_FAILED',
    'LIKE_CLICK_SUCCESS',

    'UNLIKE_CLICK_START',
    'UNLIKE_CLICK_FAILED',
    'UNLIKE_CLICK_SUCCESS'
  ],
  FULFILLED_DREAMS_LIST: [
    'LOAD_DREAMS_START',
    'LOAD_DREAMS_SUCCESS',

    'LOAD_NEXT_DREAMS_SUCCESS',
    'LOAD_DREAMS_FAILED',

    'LIKE_CLICK_START',
    'LIKE_CLICK_FAILED',
    'LIKE_CLICK_SUCCESS',

    'UNLIKE_CLICK_START',
    'UNLIKE_CLICK_FAILED',
    'UNLIKE_CLICK_SUCCESS',

    'FILTER_CHANGE',

    'HANDLE_CREATE_DREAM_CLICK',
    'HANDLE_CLOSE_DREAM_CLICK',

    'HANDLE_FIELD_CHANGE',
    'HANDLE_SELECT_PHOTO',

    'HANDLE_SAVE_IMAGE_CROPPER_MODAL',
    'HANDLE_CLOSE_IMAGE_CROPPER_MODAL',

    'HANDLE_ADD_DREAM_START',
    'HANDLE_ADD_DREAM_FAILED',
    'HANDLE_ADD_DREAM_SUCCESS'
  ],
  CERTIFICATES_LIST: [
    'LOAD_CERTIFICATES_START',
    'LOAD_CERTIFICATES_FAILED',
    'LOAD_CERTIFICATES_SUCCESS',
    'LOAD_NEXT_CERTIFICATES_SUCCESS'
  ],
  PHOTO_ALBUM: [
    'LOAD_PHOTOS_START',
    'LOAD_PHOTOS_FAILED',
    'LOAD_PHOTOS_SUCCESS',
    'LOAD_NEXT_PHOTOS_START',

    'OPEN_PHOTO_VIEWER',
    'CLOSE_PHOTO_VIEWER',

    'UPLOAD_PHOTO_SUCCESS'
  ],
  PHOTO_VIEWER: [
    'SHOW_PHOTO',
    'HIDE_PHOTO',

    'FLIP_LEFT',
    'FLIP_RIGHT',
    'PICK_BY_ID',

    'LOAD_PHOTOS_START',
    'LOAD_PHOTOS_FAILED',
    'LOAD_PHOTOS_SUCCESS'
  ],
  USER_PROFILE_SETTINGS: [
    'LOAD_SETTINGS_START',
    'LOAD_SETTINGS_FAILED',
    'LOAD_SETTINGS_SUCCESS',

    'LOAD_COUNTRIES',
    'LOAD_CITIES',

    'LOAD_COUNTRIES',
    'LOAD_CITIES',

    'CHANGE_FIELD',

    'HANDLE_SELECT_PHOTO',
    'HANDLE_SAVE_IMAGE_CROPPER_MODAL',
    'HANDLE_CLOSE_IMAGE_CROPPER_MODAL',

    'SAVE_SETTINGS_START',
    'SAVE_SETTINGS_FAILED',
    'SAVE_SETTINGS_SUCCESS'
  ],
  USER_ACCOUNT_SETTINGS: [
    'LOAD_SETTINGS_START',
    'LOAD_SETTINGS_FAILED',
    'LOAD_SETTINGS_SUCCESS',

    'LOAD_LANGUAGES',

    'CHANGE_FIELD',

    'SAVE_PASSWORD_START',
    'SAVE_PASSWORD_FAILED',
    'SAVE_PASSWORD_SUCCESS',

    'SAVE_EMAIL_START',
    'SAVE_EMAIL_FAILED',
    'SAVE_EMAIL_SUCCESS'
  ]
});
