---
dreams_env:             production
dreams_ssl_enabled:     false
dreams_nginx_conf_tpl:  "{% if dreams_ssl_enabled %}site.conf_with_ssl.j2{% else %}site.conf.j2{% endif %}"
dreams_directory:       "{{ projects_directory }}"
dreams_server:          unicorn

dreams_deploy_user:
  {
    name: dev,
    home: /home/dev,
    groups: 'dev',
    comment: 'dreams dev deploy user'
  }

dreams_web_repo:    "git@github.com:MyDreamsClub/mydreams.git"
dreams_web_branch:  'master'
dreams_web_domains: ["mydreams.club www.mydreams.club"]

dreams_web_base_dir:       "{{ dreams_directory }}/dreams"
dreams_web_releases_dir:   "{{ dreams_web_base_dir }}/releases"
dreams_web_shared_dir:     "{{ dreams_web_base_dir }}/shared"
dreams_web_bundle_dir:     "{{ dreams_web_shared_dir }}/vendor/bundle"
dreams_web_uploads_dir:    "{{ dreams_web_shared_dir }}/uploads"
dreams_web_log_dir:        "{{ dreams_web_shared_dir }}/log"
dreams_web_system_dir:     "{{ dreams_web_shared_dir }}/system"
dreams_web_pids_dir:       "{{ dreams_web_shared_dir }}/pids"
dreams_web_run_path_dir:   "{{ dreams_web_base_dir }}/current"
dreams_web_web_port:       9000

dreams_runit_services:
  - { service: "{{ dreams_server }}", name: web,    port: "{{ dreams_web_web_port }}", workers: 8, backlog: 1000 }
  - { service: sidekiq,               name: main,   queue: "-q default", concurency: 5 }
