Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder "..", "/home/vagrant/messenger", type: :nfs
  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/messenger"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "vv"
  end
end
