---
- include_vars: ../../dreams/defaults/main.yml

- name: Get previous releases version
  shell: echo `ls {{ dreams_web_releases_dir }} -1t | head -n 2 | tail -n 1`
  register: previous_release_version

- name: Symlink old release
  file: src={{ previous_release_version.stdout }} dest={{ dreams_web_run_path_dir }} state=link force=yes

- name: Restart unicorn
  shell: $SHELL -lc "sudo /usr/bin/sv restart /etc/service/dreams-unicorn-*"

# - name: Restart sidekiq
#   shell: $SHELL -lc "sudo /usr/bin/sv restart /etc/service/dreams-sidekiq-*"

- name: Notify honeybadger
  shell: 'curl -g "https://api.honeybadger.io/v1/deploys?deploy[environment]=production&deploy[local_username]=dev&deploy[revision]=b6826b8&deploy[repository]=git@github.com:MyDreamsClub/mydreams.git&api_key=d88222f6"'
