version: '2'
services:
  web:
    mem_limit: 4G
    memswap_limit: 8G
    # image: zzet/dreams:0.0.1
    build: .
    volumes:
      - .:/mydreams
    ports:
      - "3000:3000"
      - "80:8080"
    links:
      - db
      - redis
      - messenger

  db:
    image: postgres
    environment:
      POSTGRES_DB: fp
    ports:
      - "5432:5432"

  redis:
    image: redis

  messenger:
    build:
      context: ./messenger/
    ports:
      - "8081:8081"
    environment:
      LOG_LEVEL: 'info'
      RELX_REPLACE_OS_VARS: 'true'
      MYDREAMS_DATABASE_HOST: db
      MYDREAMS_DATABASE_NAME: mydreams_development
      MYDREAMS_DATABASE_USER: postgres
      MYDREAMS_DATABASE_PASSWORD: password
    command: ['./bin/messenger', 'foreground']
    links:
      - db
