frontend:
	  ./node_modules/webpack/bin/webpack.js --config ./frontend/config/webpack.$(RAILS_ENV).js

frontend_watch:
	  ./node_modules/webpack/bin/webpack.js --config ./frontend/config/webpack.$(RAILS_ENV).js --watch

.PHONY: frontend
