---
# - include_vars: ../../dreams/defaults/main.yml

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- set_fact: this_release_path="{{ dreams_web_releases_dir }}/{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
- debug: msg='New release path {{ this_release_path }}'

- name: Create new release dir
  file: path={{ this_release_path }} state=directory

- name: Update code
  sudo: no
  git: repo={{ dreams_web_repo }} dest={{ this_release_path }} version={{ dreams_web_branch }} accept_hostkey=yes
  register: git

- debug: msg='Updated repo from {{ git.before }} to {{ git.after }}'

- name: Delete log directory
  file: path={{ this_release_path }}/log state=absent

- name: Symlink shared files
  file: src={{ dreams_web_shared_dir }}/{{ item }} dest={{ this_release_path }}/{{ item }} state=link force=yes
  with_items:
    - config/database.yml
    - config/secrets.yml
    - config/unicorn.rb
    - config/dreams_secret.yml
    - config/dreams.yml
    - log
    - vendor/bundle

- name: Install bundle
  shell: $SHELL -lc 'bundle install --deployment --without="development test"'
  args:
    chdir: '{{ this_release_path }}'

- name: Run npm install
  shell: $SHELL -lc "npm install"
  args:
    chdir: '{{ this_release_path }}'
  environment:
    RAILS_ENV: '{{ dreams_env }}'
  when: inventory_hostname in groups['assets']

- name: Precompile webpack assets
  shell: $SHELL -lc "make frontend"
  args:
    chdir: '{{ this_release_path }}'
  environment:
    RAILS_ENV: '{{ dreams_env }}'
  when: inventory_hostname in groups['assets']

- name: Precompile assets
  shell: $SHELL -lc "bundle exec rake assets:precompile && tar -zcvf {{ this_release_path }}/assets.tar.gz {{ this_release_path }}/public/assets/"
  args:
    chdir: '{{ this_release_path }}'
  environment:
    RAILS_ENV: '{{ dreams_env }}'
  when: inventory_hostname in groups['assets']

- name: Fetch assets
  fetch: src='{{ this_release_path }}/assets.tar.gz' dest=/tmp/assets.tar.gz flat=yes
  when: inventory_hostname in groups['assets']

- name: Unarchive assets
  unarchive: src=/tmp/assets.tar.gz dest='/'
  when: inventory_hostname in groups['application']

- name: cleanup
  local_action: shell rm -rf /tmp/assets.tar.gz

- name: Migrate database
  shell: $SHELL -lc "bundle exec rake db:migrate"
  args:
    chdir: '{{ this_release_path }}'
  when: inventory_hostname in groups['dbmigrate']
  environment:
    RAILS_ENV: '{{ dreams_env }}'
  ignore_errors: true

- name: Symlink new release
  file: src={{ this_release_path }} dest={{ dreams_web_run_path_dir }} state=link force=yes

- name: Restart unicorn
  shell: $SHELL -lc "sudo /usr/bin/sv restart /etc/service/dreams-puma-*"
  when: inventory_hostname in groups['application']
  ignore_errors: true

- name: Restart sidekiq
  shell: $SHELL -lc "sudo /usr/bin/sv restart /etc/service/dreams-sidekiq-*"
  when: inventory_hostname in groups['bg']
  ignore_errors: true

- name: Cleanup
  shell: "ls -1t {{ dreams_web_releases_dir }}|tail -n +{{ keep_releases + 1 }}|xargs rm -rf"
  args:
    chdir: '{{ dreams_web_releases_dir }}'

# - name: Notify honeybadger
#   shell: 'curl -g "https://api.honeybadger.io/v1/deploys?deploy[environment]={{ dreams_env }}&deploy[local_username]={{ username_on_the_host.stdout }}&deploy[revision]={{ git.after }}&deploy[repository]=git@github.com:MyDreamsClub/mydreams.git&api_key=d88222f6"'
