---
- name: Adds erlang-solutions repository
  become: yes
  apt_repository:
    repo: deb http://packages.erlang-solutions.com/{{ansible_lsb.id | lower}} {{ansible_lsb.codename}} contrib
    state: present

- name: Adds the Erlang Solutions public key for apt-secure
  become: yes
  apt_key:
    url: http://packages.erlang-solutions.com/{{ansible_lsb.id | lower}}/erlang_solutions.asc
    state: present

- name: Install erlang
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - erlang
