---
galaxy_info:
  author: Andrey Kumanyaev
  description:
  company: dreams
  license: CC-BY
  min_ansible_version: 1.9
  platforms:
    - name: Debian
      versions:
        - squeeze
  categories:
    - development
    - monitoring
    - web
  dependencies: []
      # List your role dependencies here, one per line.
      # Be sure to remove the '[]' above if you add dependencies
      # to this list.
