defaults: &defaults
  payments:
    yandex_kassa:
      url: https://demomoney.yandex.ru/eshop.xml
      secret: 123
      shopId: 124
      scid: 125

production:
  <<: *defaults
  payments:
    yandex_kassa:
      url: https://money.yandex.ru/eshop.xml
      secret: Z4Rfa4phELznbV
      shopId: 116700
      scid: 49318

staging:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
