---
- set_fact:
    this_release_path: "{{ messenger_releases_dir }}/{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
- debug: msg='New release path {{ this_release_path }}'

- name: Creat git repo for sparse checkout
  command: git init
  args:
    chdir: "{{ messenger_src_dir }}"
    creates: "{{ messenger_src_dir }}/.git"
  register: git_init

- name: Add git remote
  command: git remote add origin {{ messenger_git_repo }}
  args:
    chdir: "{{ messenger_src_dir }}"
  when: "{{ git_init.changed }}"

- name: Enable sparse-checkout
  command: git config core.sparsecheckout true
  args:
    chdir: "{{ messenger_src_dir }}"

- name: Adds messenger to sparse-checkout
  lineinfile:
    create: yes
    dest: "{{ messenger_src_dir }}/.git/info/sparse-checkout"
    line: messenger
    state: present

# - name: Update code
#   command: git pull origin {{ messenger_git_branch }}
#   args:
#     chdir: "{{ messenger_src_dir }}"

- name: Update code
  sudo: no
  git: repo={{ messenger_git_repo }} dest={{ messenger_src_dir }} version={{ messenger_git_branch }} accept_hostkey=yes
  register: git
- debug: msg='Updated repo from {{ git.before }} to {{ git.after }}'

- name: Prepare build
  file:
    path: "{{ messenger_src_dir }}/messenger/_build"
    state: absent

- name: Build
  command: "./rebar3 release --dev-mode false --output-dir {{ messenger_releases_dir }} --relname {{ messenger_release_name }}"
  args:
    chdir: "{{ messenger_src_dir }}/messenger"

- name: Rename release
  command: mv "{{ messenger_releases_dir }}/{{ messenger_release_name }}" {{ this_release_path }}

- name: Symlink new release
  file:
    src: "{{ this_release_path }}"
    dest: "{{ messenger_run_path_dir }}"
    state: link
    force: yes
    owner: "{{ messenger_deploy_user.name }}"
    group: "{{ messenger_deploy_user.name }}"

- name: Restart messenger
  shell: $SHELL -lc "sudo /usr/bin/sv restart /etc/service/messenger"
  when: inventory_hostname in groups['messenger']
  ignore_errors: true

- name: Cleanup
  shell: "ls -1t {{ messenger_releases_dir }}|tail -n +{{ keep_releases + 1 }}|xargs rm -rf"
  args:
    chdir: '{{ messenger_releases_dir }}'
