---
projects_directory: /srv/apps

group_name: dev
user_name: dev
user_home_path: /home/dev

rbenv:
  env: user
  version: v0.4.0
  ruby_version: 2.3.0

users:
  - { name: dev,  home: /home/dev, shell: /bin/bash, groups: 'dev', comment: "Dreams dev user" }

rbenv_users:
  - dev

openssl_version: "1.0.2e"

nginx_large_client_header_buffers: "4 8k"
nginx_client_body_buffer_size: '10k'
nginx_client_max_body_size: "32m"

nginx_access_logs:
  - name: 'combined_plus'
    format: >
      '$remote_addr - $remote_user [$time_local]'
      ' "$request" $status $body_bytes_sent "$http_referer"'
      ' "$http_user_agent" $request_time $upstream_cache_status'
      ' [$upstream_response_time]'
    options: null
    filename: "access.log"

ntp_config_server:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
  - 0.north-america.pool.ntp.org
  - 1.north-america.pool.ntp.org
  - 2.north-america.pool.ntp.org
  - 3.north-america.pool.ntp.org
