---
postgresql_version: 9.4
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'

postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_cluster_name: "main"
postgresql_cluster_reset: false

postgresql_max_connections: 200
postgresql_shared_buffers: 16GB # min 128kB
postgresql_effective_cache_size: 48GB
postgresql_work_mem: 4MB   # min 64kB
postgresql_maintenance_work_mem: 2GB  # min 1MB
postgresql_checkpoint_segments: 32     # (<= 9.4) in logfile segments, min 1, 16MB each
postgresql_checkpoint_completion_target: 0.9   # checkpoint target duration, 0.0 - 1.0
postgresql_wal_buffers: 16MB     # min 32kB, -1 sets based on shared_buffers
postgresql_default_statistics_target: 100  # range 1-10000
postgresql_shared_preload_libraries: ['pg_stat_statements']
postgresql_pg_stat_statements:
  - max: 500
    track: top
    track_utility: true
    save: false
postgresql_track_io_timing:           on   # (>= 9.2)

postgresql_databases:
  - name: dreams_production
    hstore: yes        # flag to install the hstore extension on this database (yes/no)
    uuid_ossp: no      # flag to install the uuid-ossp extension on this database (yes/no)
    citext: no         # flag to install the citext extension on this database (yes/no)

# List of users to be created (optional)
postgresql_users:
  - name: app
    encrypted: no       # denotes if the password is already encrypted.

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: app                 # user name
    password: tA3UjcugmhgqK6
    db: dreams_production       # database
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags
