---
postgresql_version: 9.4
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'

postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_cluster_name: "main"
postgresql_cluster_reset: false

postgresql_max_connections: 200

postgresql_databases:
  - name: dreams_staging
    hstore: yes        # flag to install the hstore extension on this database (yes/no)
    uuid_ossp: no      # flag to install the uuid-ossp extension on this database (yes/no)
    citext: no         # flag to install the citext extension on this database (yes/no)

# List of users to be created (optional)
postgresql_users:
  - name: app
    encrypted: no       # denotes if the password is already encrypted.

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: app                 # user name
    password: tA3UjcugmhgqK6
    db: dreams_staging          # database
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags

redis_version: 3.0.7
redis_bind: 127.0.0.1

dreams_env:             staging
dreams_ssl_enabled:     false
dreams_nginx_conf_tpl:  "{% if dreams_ssl_enabled %}site.conf_with_ssl.j2{% else %}site.conf.j2{% endif %}"
dreams_directory:       "{{ projects_directory }}"
dreams_server:          puma

dreams_deploy_user:
  {
    name: dev,
    home: /home/dev,
    groups: 'dev',
    comment: 'dreams dev deploy user'
  }

dreams_web_repo:    "git@github.com:MyDreamsClub/mydreams.git"
dreams_web_branch:  'staging'
dreams_web_domains: ["staging.mydreams.club"]

dreams_web_base_dir:       "{{ dreams_directory }}/dreams"
dreams_web_releases_dir:   "{{ dreams_web_base_dir }}/releases"
dreams_web_shared_dir:     "{{ dreams_web_base_dir }}/shared"
dreams_web_bundle_dir:     "{{ dreams_web_shared_dir }}/vendor/bundle"
dreams_web_uploads_dir:    "{{ dreams_web_shared_dir }}/uploads"
dreams_web_log_dir:        "{{ dreams_web_shared_dir }}/log"
dreams_web_system_dir:     "{{ dreams_web_shared_dir }}/system"
dreams_web_pids_dir:       "{{ dreams_web_shared_dir }}/pids"
dreams_web_run_path_dir:   "{{ dreams_web_base_dir }}/current"
dreams_web_web_port:       9000

dreams_runit_services:
  - { service: "{{ dreams_server }}", name: web,    port: "{{ dreams_web_web_port }}", workers: 8, min_threads: 16, max_threads: 32, backlog: 1000 }
  - { service: sidekiq,               name: main,   queue: "-q default", concurency: 5 }
